cluster.name: "elasticsearch-cluster"

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

transport.host: localhost
network.host: 0.0.0.0
network.bind_host: '0.0.0.0'
transport.bind_host: 0.0.0.0
transport.tcp.port: 9300
http.port: 9200
indices.query.bool.max_clause_count: 10240
bootstrap.system_call_filter: false
# xpack.security.audit.enabled: false
# xpack.security.enabled: false